version: "3"
services:
  app:
    build: .
    tty: true
    # command: node /app/index.js "/input/c4611 sample explain.pdf"
    command: /app/auto-editor.sh
    volumes: 
      - ./app:/app/
      - ./cache:/cache/
      # - ./input/:/input/
      - /mnt/microsd/ext4/download/:/input/